### ISSUE TITLE
How do I specify asset_id?

### ISSUE THREAD

**Issue by NishidaRyu416** [haw-itn/openassets-ruby#20]
I want to specify asset_id when I issue.
Whereas I don't know how to do that.
Please answer sir

**Comment by azuchi** [comment]
Because asset_id is calculated automatically from scriptPubkey (:= address), it can not be specified directly with issue_asset.

Instead you can specify the address used to calculate asset_id.

**Comment by NishidaRyu416** [comment]
Thank you for answering.
I figured it out at length.
Incidentally,how should I specify asset_id on an Asset definition file when I first issue assets.

**Comment by azuchi** [comment]
Since asset_id can be calculated from scriptPubkey, so you can calculate it from the `from address` specified by issue_asset.

**Comment by NishidaRyu416** [comment]
I understood.
Whereas I can't find out how I can specify asset_id on an `Asset definition file` when I don't know what the `asset_id` is.

**Comment by azuchi** [comment]
maybe you don't understand.
`issue_asset` requires `from address`. you can calculate asset id from the public key used by `from address`, using `Bitcoin::Util#generate_asset_id` or `pubkey_hash_to_asset_id`.

**Comment by NishidaRyu416** [comment]
So you mean that one `asset_id` can exist per a `bitcoin_address` therefore various `asset_ids` can't exist?

**Comment by azuchi** [comment]
> So you mean that only one asset_id can exist per a bitcoin_address

yes, 1 address corresponds to 1 asett_id.

>  therefore various asset_ids can't exist?

Addresses can be generated almost infinitely. Therefore, the number of asset_id that can be generated is infinite.

For details, please check the specification of Open Asset Protocol.
https://github.com/OpenAssets/open-assets-protocol/blob/master/specification.mediawiki#Protocol_Overview

>  Incidentally can I calculate asset_id with #address_to_asset_id(btc_address) ⇒ Object as well?

Such methods are not implemented in openassets-ruby and no plan implements it.

**Comment by NishidaRyu416** [comment]
Thank you for detailed information 
As you said,I calculated the asset_id but the asset_id wasn't  same as the asset_id which was shown by "#get_balance"

**Comment by NishidaRyu416** [comment]
```
    btc_address="mr2TrupRLKLJUoCu3FmPkeaT3TGNw6BgST"
     oa_address= OpenAssets.address_to_oa_address(btc_address)
     oa_address
     api.get_balance(oa_address)
    asset_id = generate_asset_id(api,btc_address)
    puts "asset_id:#{asset_id}"
    tx= api.issue_asset(oa_address,100,'u=https://goo.gl/GwJ6hM',oa_address, nil, 'broadcast')
    puts tx


  private

  def generate_asset_id(api,btc_address)
  private_key=api.provider.dumpprivkey(btc_address)
  pub_key = regenerate_public_key(private_key)

  hash = hash160(pub_key)

  script = hash160(["76", "a9", "14", hash, "88", "ac"].join)

  script = 23.to_s(16) + script
  asset_id = encode_base58(script + checksum(script))
    return asset_id
  end
```

**Comment by azuchi** [comment]
> private_key=api.provider.dumpprivkey(btc_address)

dumpprivkey returns private key with WIF format. so you should convert it like folloows

```
key = Bitcoin::Key.from_base58(api.provider.dumpprivkey(btc_address))
pub_key = key.pub
```

**Comment by NishidaRyu416** [comment]
Although I tried as you said still incorrect 'asset_id' was calclated.

**Comment by azuchi** [comment]
Since I do not know the actual value, I can not comment, but if you know the public key, simply asset_id can be calculated with the following code.

```ruby
include OpenAssets::Util

generate_asset_id(pubkey)
```

**Comment by NishidaRyu416** [comment]
Oh that's quite good thanks to you I could calculate successfully!!!
