### ISSUE TITLE
When I upgraded bitcoin-cli, I got the error below.

### ISSUE THREAD

**Issue by NishidaRyu416** [haw-itn/openassets-ruby#24]
Thank you for helping every time,  
```
{"code"=>-32, "message"=>"signrawtransaction is deprecated and will be fully removed in v0.18. To use signrawtransaction in v0.17, restart bitcoind with -deprecatedrpc=signrawtransaction.\nProjects should transition to using signrawtransactionwithkey and signrawtransactionwithwallet before upgrading to v0.18"}
```
I could understand that I can continue using the`send_bitcoin` method, after specifying the ` -deprecatedrpc=signrawtransaction`, but I wonder if this will be fixed on openassets-ruby.

So do you have the plan to fix it?

**Comment by azuchi** [comment]
This change seems to be applied in Bitcoin Core 0.17.0, so I will consider it when 0.17.0 is released.
