### ISSUE TITLE
InsufficientAssetQuantityError for second transaction / how to deal with unconfirmed transactins?

### ISSUE THREAD

**Issue by bumi** [haw-itn/openassets-ruby#3]
I am currently dealing with the following scenario: 

I have a wallet that has received a quantity of 100 assets in one transaction. Now once I have done a transaction I receive an `InsufficientAssetQuantityError` exception for the next send transaction until the first transaction is confirmed. 
As colorcore by default we only get transactions with a 1-9999999 confirmations when we call [list_unspent](https://github.com/haw-itn/openassets-ruby/blob/0b1dcc8bd8f8d40cb4636c9c4b2a26bf378a670f/lib/openassets/provider/bitcoin_core_provider.rb#L35).  (Assuming) because the whole quantity of 100 is used as an input for the first transaction we do not find any assets (as `list_unspent` returns nothing) until the transaction is confirmed. This causes the exception even though actually the wallet has enough assets to send.

Probably this is a general open assets problem, but what is the best way to deal with that issue? 
Shouldn't it be OK to use transactions with zero confirmations as input? (1 confirmation is probably safer but it still can happen that the chain forks.)
bitcoind knows about the sent transaction and about the change that can be used as input for the next transaction?

(sorry if this is the wrong place to raise this issue, if so where should I post it? - also I thought others might have run in the same problem)

**Comment by azuchi** [comment]
The specification of the Open Assets Protocol, since the number of confirmation has not been defined, I think that there is no problem even if allowed to zero confirmation. However, because the risk is there, use the necessary self-judgment.

I change to be able to set the minimum confirmation number in the API of openassets-ruby, so your probrem will be solved?

**Comment by bumi** [comment]
ok, thanks!
I was thinking what would be the best way to make it configurable. passing it to `send_asset` seems not easily possible because quite some methods are involved (transfer_asset, transfer, TransactionBuilder, ..). 
maybe we could make the default parameter for `list_unspent` globally configurable?

**Comment by azuchi** [comment]
thanks, but I do not want to increase the argument to each api, so add configuration options(min_confirmation, max_confirmation).
https://github.com/haw-itn/openassets-ruby/commit/ecb8df95ecc401c09a33febaf6534fe4653e74d5
